// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMNXSHmYwVTgObxwDxX9g1rgfmrUilFY',
    appId: '1:53229438855:web:3cb06353498403f54d7522',
    messagingSenderId: '53229438855',
    projectId: 'fir-firsttst',
    authDomain: 'fir-firsttst.firebaseapp.com',
    storageBucket: 'fir-firsttst.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOHTpnMGTv2ql7-iKs3sgqb4DFVcBezE',
    appId: '1:53229438855:android:37c413a72c0d5e8f4d7522',
    messagingSenderId: '53229438855',
    projectId: 'fir-firsttst',
    databaseURL: 'https://fir-firsttst-default-rtdb.firebaseio.com',
    storageBucket: 'fir-firsttst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCf9PaO0dckKg-jOXejjeqiAs0X1XBtk',
    appId: '1:53229438855:ios:88a62bbf71ba7fd24d7522',
    messagingSenderId: '53229438855',
    projectId: 'fir-firsttst',
    databaseURL: 'https://fir-firsttst-default-rtdb.firebaseio.com',
    storageBucket: 'fir-firsttst.appspot.com',
    iosBundleId: 'com.example.libraryApp',
  );

}